[build]
  # The directory where your pre-built files are located
  publish = "build/web"
  # No build command needed as we're using pre-built files
  command = ""

# Handle client-side routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 