name: jaouda_boujdour_app
description: "A new Flutter project for Jaouda Boujdour"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Routing
  go_router: ^13.1.0
  
  # Backend & Authentication
  supabase_flutter: ^2.3.1
  
  # UI Components
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.0
  flutter_spinkit: ^5.2.0
  google_maps_flutter: ^2.5.3
  
  # Utilities
  uuid: ^3.0.7
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  geolocator: ^10.1.0
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_map_marker_cluster: ^1.3.6
  flutter_map_heatmap: ^0.0.7
  fl_chart: ^0.66.2
  pdf: ^3.10.7
  share_plus: ^7.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.10
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  generate: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # Commented out fonts temporarily
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

dependency_overrides:
  collection: ^1.18.0
  meta: ^1.11.0
  vector_math: ^2.1.4
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_color_utilities: ^0.12.0